Repository IgniteUI/igniteui-angular-wrappers, pull requests merged in 2018-07, with the labels that each got.

#278 Update @types/ignite-ui to ^18.1.1
  dist/npm/package.json
Labels: status: verified

#279 Improve data binding for data source widgets
  src/igcontrolbase/igcontrolbase.ts
  src/igdatachart/igdatachart.component.ts
  src/igdoughnutchart/igdoughnutchart.component.ts
  src/igfunnelchart/igfunnelchart.component.ts
  src/igmap/igmap.component.ts
  src/igpiechart/igpiechart.component.ts
  src/igpivotdataselector/igpivotdataselector.component.ts
  src/igpivotgrid/igpivotgrid.component.ts
  src/igsparkline/igsparkline.component.ts
  src/igtilemanager/igtilemanager.component.ts
  tests/unit/igdatachart/chart.spec.ts
  tests/unit/igdoughnutchart/doughnutchart.spec.ts
  tests/unit/igfunnerchart/funnelchart.spec.ts
  tests/unit/igmap/map.spec.ts
  tests/unit/igpiechart/piechart.spec.ts
  tests/unit/igpivotdataselector/pivotdataselector.spec.ts
  tests/unit/igpivotgrid/pivotgrid.spec.ts
  tests/unit/igsparkline/sparkline.spec.ts
  tests/unit/igtilemanager/tilemanager.spec.ts
Labels: status: verified

#280 Improve extracting valueKey when model value is applied
  src/igcombo/igcombo.component.ts
  tests/unit/igcombo/combo.spec.ts
Labels: status: verified

#283 build(npm): update npm deploy token
  .travis.yml
Labels: npm

#281 Ensure element is attached to DOM when destroying igZoombar
  dist/npm/package.json
  src/igcontrolbase/igcontrolbase.ts
  tests/unit/igdatachart/chart.spec.ts
Labels: status: verified, zoombar
